
- name: Install dependencies
      run: |
        sudo apt-get update
        # Принудительно устанавливаем libunwind-dev, исправляя сломанные зависимости
        sudo apt-get install -y --fix-broken libunwind-dev
        
        # Теперь ставим всё остальное
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libsqlite3-dev \
          sqlite3 \
          bzip2 \
          libbz2-dev \
          libssl-dev \
          openssl \
          libgdbm-dev \
          libgdbm-compat-dev \
          liblzma-dev \
          libreadline-dev \
          libncursesw5-dev \
          libffi-dev \
          uuid-dev \
          libgpm2 \
          unzip \
          zip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          ccache
